In [ ]:
# 今天的任务主要是解决 setting with copy warning

""" 
.copy()直接将一个dataframe或者series给copy复制过来
setting with copy warning 总是出现在链式索引调用里面。规避掉这个，就基本能解决百分之九十的问题了
这个报错出现的本质在于，pandas没办法判定究竟是在原始数据上进行操作，还是在副本数据上进行操作。

然后 .copy() and .iloc，loc
分别是复制一份数据进行加工，或者在原始数据进行加工

然后今天的主线任务就是，用.iloc()主要通过数字来定位，
.loc()主要通过标签来定位




"""

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    'ticker':['AAPL']*3+['GOOGL']*3,
    'date':pd.date_range('2025-04-01',periods = 3).tolist()*2,
    'close':np.random.randn(6)*2+150
})

df

  ticker       date       close
0   AAPL 2025-04-01  150.993428
1   AAPL 2025-04-02  149.723471
2   AAPL 2025-04-03  151.295377
3  GOOGL 2025-04-01  153.046060
4  GOOGL 2025-04-02  149.531693
5  GOOGL 2025-04-03  149.531726

In [9]:
df.loc[df['ticker'] == 'AAPL','close'] = 0
df

  ticker       date       close
0   AAPL 2025-04-01    0.000000
1   AAPL 2025-04-02    0.000000
2   AAPL 2025-04-03    0.000000
3  GOOGL 2025-04-01  153.046060
4  GOOGL 2025-04-02  149.531693
5  GOOGL 2025-04-03  149.531726

In [19]:
filtered1 = df.loc[df['close'] > 150,].copy()
filtered1['return'] = filtered1['close'].pct_change()
filtered1

  ticker       date      close  return
3  GOOGL 2025-04-01  153.04606     NaN

In [20]:
subset = df[df['ticker'] == 'AAPL'].copy()
subset['log_return'] = np.log(subset['close'] / subset['close'].shift(1))
subset

  ticker       date  close  log_return
0   AAPL 2025-04-01    0.0         NaN
1   AAPL 2025-04-02    0.0         NaN
2   AAPL 2025-04-03    0.0         NaN