In [1]:
import pandas as pd
import numpy as np
import os
np.random.seed(42)
arrays = [
    ['bar','bar','baz','baz','foo','foo','qux','qux'],
    ['one','two','one','two','one','two','one','two'],
]
index = pd.MultiIndex.from_arrays(arrays,names = ['first','second'])
#并且multiindex会将重复的东西自动合并，只显示一次
s = pd.Series(np.random.randn(8),index = index)
print(s)

first  second
bar    one       0.496714
       two      -0.138264
baz    one       0.647689
       two       1.523030
foo    one      -0.234153
       two      -0.234137
qux    one       1.579213
       two       0.767435
dtype: float64

In [2]:
grouped = s.groupby(level = 0)#这里的索引表示第一个，即‘first’
print(grouped.sum())

first
bar    0.358450
baz    2.170718
foo   -0.468290
qux    2.346648
dtype: float64

In [4]:
s.groupby(level = 'second').sum()

second
one    2.489462
two    1.918063
dtype: float64

In [5]:
arrays_1 = [
    ['bar','bar','baz','baz','foo','foo','qux','qux'],
    ['doo','doo','bee','bee','bop','bop','bop','bop'],
    ['one','two','one','two','one','two','one','two'],
    
]

index_1 = pd.MultiIndex.from_arrays(arrays_1,names = ['first','second','third'])

s_1 = pd.Series(np.random.randn(8),index = index_1)
s_1

s_1.groupby(level = ['first','second']).sum()

first  second
bar    doo       0.073086
baz    bee      -0.929147
foo    bop      -1.671318
qux    bop      -2.287205
dtype: float64

In [6]:
s_1.groupby(['first','second']).sum()
#从这里可以看出，其实可以不写level zheyiju

first  second
bar    doo       0.073086
baz    bee      -0.929147
foo    bop      -1.671318
qux    bop      -2.287205
dtype: float64

In [7]:
##loc 是横向取，groupby是纵向取，loc[],后面，可以接很多东西
#xs.也是一种很重要的方法

ValueError: No axis named bar for object type Series

In [10]:


np.random.seed(42)

data = {
    "ticker":['AAPL']*5+['GOOGL']*5+['MSFT']*5,
    "date":pd.date_range('2025-04-01',periods=5).tolist()*3,
    #这里的tolist是转换成普通的python列表，*3表示重复三次
    "close":np.random.randn(15)*2+150,
    #这里是生成15个，标准差为2，均值为150的随机数
    "volume":np.random.randint(1000,10000,15)

}
df = pd.DataFrame(data)

df

   ticker       date       close  volume
0    AAPL 2025-04-01  150.993428    3558
1    AAPL 2025-04-02  149.723471    8849
2    AAPL 2025-04-03  151.295377    3047
3    AAPL 2025-04-04  153.046060    3747
4    AAPL 2025-04-05  149.531693    1189
5   GOOGL 2025-04-01  149.531726    3734
6   GOOGL 2025-04-02  153.158426    4005
7   GOOGL 2025-04-03  151.534869    5658
8   GOOGL 2025-04-04  149.061051    2899
9   GOOGL 2025-04-05  151.085120    8734
10   MSFT 2025-04-01  149.073165    2267
11   MSFT 2025-04-02  149.068540    2528
12   MSFT 2025-04-03  150.483925    4556
13   MSFT 2025-04-04  146.173440    4890
14   MSFT 2025-04-05  146.550164    9838

In [11]:
df_multi = df.set_index(['ticker','date']).sort_index()
#set_index这里是将ticker和date提取出来作为索引，而close和volume仍然作为列名，（原本的数据默认的索引为0，1，

df_multi

                        close  volume
ticker date
AAPL   2025-04-01  150.993428    3558
       2025-04-02  149.723471    8849
       2025-04-03  151.295377    3047
       2025-04-04  153.046060    3747
       2025-04-05  149.531693    1189
GOOGL  2025-04-01  149.531726    3734
       2025-04-02  153.158426    4005
       2025-04-03  151.534869    5658
       2025-04-04  149.061051    2899
       2025-04-05  151.085120    8734
MSFT   2025-04-01  149.073165    2267
       2025-04-02  149.068540    2528
       2025-04-03  150.483925    4556
       2025-04-04  146.173440    4890
       2025-04-05  146.550164    9838

In [13]:
task_4 = df_multi.loc[('AAPL',slice('2025-04-01','2025-04-03')),:]
#元组第一个是ticker，第二个是使用slice确定切割的范围，：表示取所有
task_4

                        close  volume
ticker date
AAPL   2025-04-01  150.993428    3558
       2025-04-02  149.723471    8849
       2025-04-03  151.295377    3047

In [14]:
task_5 = df_multi.xs('2025-04-02',level = 'date')['close']
#xs表示直接跨层级提取‘2025-04-02’的数据，
task_5

ticker
AAPL     149.723471
GOOGL    153.158426
MSFT     149.068540
Name: close, dtype: float64

In [16]:
task_6 = df_multi.groupby(level = 0)['close'].apply(lambda x: x/x.iloc[0]-1)
#iloc是进行数数，
#.apply 是对每组你想操作的数据执行你想进行的操作
task_6

ticker  ticker  date
AAPL    AAPL    2025-04-01    0.000000
                2025-04-02   -0.008411
                2025-04-03    0.002000
                2025-04-04    0.013594
                2025-04-05   -0.009681
GOOGL   GOOGL   2025-04-01    0.000000
                2025-04-02    0.024254
                2025-04-03    0.013396
                2025-04-04   -0.003148
                2025-04-05    0.010388
MSFT    MSFT    2025-04-01    0.000000
                2025-04-02   -0.000031
                2025-04-03    0.009464
                2025-04-04   -0.019452
                2025-04-05   -0.016925
Name: close, dtype: float64

In [17]:
import pandas as pd
import os

class DataProcessor1:
    def __init__(self):
        self.data_path = "./data/"
    
    def load_data1(self, return_list=True):
        df_list = []
        
        for file in os.listdir(self.data_path):
            if file.endswith(".csv"):
                file_path = os.path.join(self.data_path, file)
                
                # 关键：跳过第二行垃圾数据
                df = pd.read_csv(file_path, skiprows=[1])
                
                ticker = file.replace(".csv", "")
                df["ticker"] = ticker
                
                # 处理日期
                df['date'] = pd.to_datetime(df['Date'])
                
                # 数字列自动转换（pandas 会自动处理）
                # 如果还有问题，用这个：
                # df['Close'] = pd.to_numeric(df['Close'], errors='coerce')
                
                
                df_list.append(df)
                #pd.concat返回的是一个DataFrame，而不是list,这里的list是指数据结构中的list
        
        return df_list if return_list else pd.concat(df_list, ignore_index=True)
    #这里返回的df_list中，每个元素都是一个DataFrame
    def align_price(self, df_list, price_col='Close', fill_method='ffill'):
        tickers = [df['ticker'].iloc[0] for df in df_list]
        #从每个列表中取出ticker，并且只用取一个就够了，所以用,iloc[0]
        
        combined = pd.concat(
            [df.set_index('date')[price_col] for df in df_list],
            axis=1,
            keys=tickers
        )
        
        if fill_method == 'ffill':
            combined = combined.ffill()
        
        combined.index = pd.to_datetime(combined.index)
        combined = combined.sort_index()
        
        return combined


if __name__ == '__main__':
    processor = DataProcessor1()
    
    df_list = processor.load_data1(return_list=True)
    aligned_price = processor.align_price(df_list, price_col='Close')
    print(aligned_price.head())
    print(f"\n数据形状: {aligned_price.shape}")

FileNotFoundError: [Errno 2] No such file or directory: './data/'