In [ ]:
"""learning the usage of reindex"""
"""如果原来就存在的index，reindex之后值还是对应的，出现的新的index，其值为NaN"""
"""the usage of bfill（后面的值往前填)且只填原来没出现的索引的 原来的索引有的不填 ,ffill（前面的值往后填）"""

In [12]:
import pandas as pd
index = ['FireFox','Chrome','Safari','IE10','Konqueror']
columns = ["https_status","response_time"]
df = pd.DataFrame(
    [[200,0.04],[200,0.02],[404,0.07],[404,0.08],[301,1.0]],
    columns = columns,
    index = index
)
df

           https_status  response_time
FireFox             200           0.04
Chrome              200           0.02
Safari              404           0.07
IE10                404           0.08
Konqueror           301           1.00

In [13]:
new_index = ['Safari','Iceweasel','Comodo Dragon','IE10','Chrome']
df.reindex(new_index)

               https_status  response_time
Safari                404.0           0.07
Iceweasel               NaN            NaN
Comodo Dragon           NaN            NaN
IE10                  404.0           0.08
Chrome                200.0           0.02

In [14]:
df.reindex(new_index, fill_value = 0)

               https_status  response_time
Safari                  404           0.07
Iceweasel                 0           0.00
Comodo Dragon             0           0.00
IE10                    404           0.08
Chrome                  200           0.02

In [15]:
df.reindex(new_index,fill_value = 'missing')

              https_status response_time
Safari                 404          0.07
Iceweasel          missing       missing
Comodo Dragon      missing       missing
IE10                   404          0.08
Chrome                 200          0.02

In [18]:
df.reindex(columns = ['https_status','usr_agent'])

           https_status  usr_agent
FireFox             200        NaN
Chrome              200        NaN
Safari              404        NaN
IE10                404        NaN
Konqueror           301        NaN

In [19]:
df.reindex(['https_status','user_agent'],axis = 'columns')

           https_status  user_agent
FireFox             200         NaN
Chrome              200         NaN
Safari              404         NaN
IE10                404         NaN
Konqueror           301         NaN

In [22]:
date_index = pd.date_range('1/1/2010',periods = 6,freq = 'D')
df2 = pd.DataFrame(
    {'Prices':[100,101,np.nan,100,89,88]},
    index= date_index
)
df2

            Prices
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0

In [23]:
date_index2 =pd.date_range('12/29/2009',periods = 10,freq = 'D')
df2.reindex(date_index2)

            Prices
2009-12-29     NaN
2009-12-30     NaN
2009-12-31     NaN
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
2010-01-07     NaN

In [25]:
df2.reindex(date_index2,method = 'ffill')

            Prices
2009-12-29     NaN
2009-12-30     NaN
2009-12-31     NaN
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
2010-01-07    88.0

In [ ]:
# 模拟停牌：假设 MSFT 在 2025-04-03 没有数据 (删掉那一行)
df_missing = df.drop(index=df[(df.ticker=='MSFT') & (df.date=='2025-04-03')].index)

# 【任务 7】重构这个 DataFrame，确保每个 ticker 都有完整的 2025-04-01 到 2025-04-05 这 5 天数据
# 提示：
# 1. 先用 groupby('ticker')
# 2. 对每个组 apply 一个函数，函数里用 set_index('date').reindex(full_date_range)
# 3. 缺失的 close 用前值填充，缺失的 volume 填 0
# --- 你的代码 (这道题很难，允许花 2 小时攻克) ---

In [26]:
import pandas as pd
import numpy as np

np.random.seed(42)

data = {
    "ticker":['APPLE']*5+['GOOGLE']*5+['MSFT']*5,
    "date":pd.date_range('2025-04-01',periods=5).tolist()*3,
    #这里的tolist是转换成普通的python列表，*3表示重复三次
    "close":np.random.randn(15)*2+150,
    #这里是生成15个，标准差为2，均值为150的随机数
    "volume":np.random.randint(1000,10000,15)

}
df_1 = pd.DataFrame(data)
df_1

    ticker       date       close  volume
0    APPLE 2025-04-01  150.993428    3558
1    APPLE 2025-04-02  149.723471    8849
2    APPLE 2025-04-03  151.295377    3047
3    APPLE 2025-04-04  153.046060    3747
4    APPLE 2025-04-05  149.531693    1189
5   GOOGLE 2025-04-01  149.531726    3734
6   GOOGLE 2025-04-02  153.158426    4005
7   GOOGLE 2025-04-03  151.534869    5658
8   GOOGLE 2025-04-04  149.061051    2899
9   GOOGLE 2025-04-05  151.085120    8734
10    MSFT 2025-04-01  149.073165    2267
11    MSFT 2025-04-02  149.068540    2528
12    MSFT 2025-04-03  150.483925    4556
13    MSFT 2025-04-04  146.173440    4890
14    MSFT 2025-04-05  146.550164    9838

In [30]:
# 模拟停牌：假设 MSFT 在 2025-04-03 没有数据 (删掉那一行)
df_missing = df_1.drop(index=df_1[(df_1.ticker=='MSFT') & (df_1.date=='2025-04-03')].index)
df_missing
# 【任务 7】重构这个 DataFrame，确保每个 ticker 都有完整的 2025-04-01 到 2025-04-05 这 5 天数据
# 提示：
# 1. 先用 groupby('ticker')
# 2. 对每个组 apply 一个函数，函数里用 set_index('date').reindex(full_date_range)
# 3. 缺失的 close 用前值填充，缺失的 volume 填 0
# --- 你的代码 (这道题很难，允许花 2 小时攻克) ---

    ticker       date       close  volume
0    APPLE 2025-04-01  150.993428    3558
1    APPLE 2025-04-02  149.723471    8849
2    APPLE 2025-04-03  151.295377    3047
3    APPLE 2025-04-04  153.046060    3747
4    APPLE 2025-04-05  149.531693    1189
5   GOOGLE 2025-04-01  149.531726    3734
6   GOOGLE 2025-04-02  153.158426    4005
7   GOOGLE 2025-04-03  151.534869    5658
8   GOOGLE 2025-04-04  149.061051    2899
9   GOOGLE 2025-04-05  151.085120    8734
10    MSFT 2025-04-01  149.073165    2267
11    MSFT 2025-04-02  149.068540    2528
13    MSFT 2025-04-04  146.173440    4890
14    MSFT 2025-04-05  146.550164    9838

In [77]:
full_date_range = pd.date_range('2025-04-01', periods=5)

df_new = df_missing.groupby('ticker').apply(lambda x: 
    x.set_index('date')
     .reindex(full_date_range)
     .fillna({'volume': 0})  # 👈 移到第一顺位！先填volume
     .ffill()                # 👈 后填close！顺序颠倒
).reset_index()
df_new

    ticker    level_1       close  volume
0    APPLE 2025-04-01  150.993428  3558.0
1    APPLE 2025-04-02  149.723471  8849.0
2    APPLE 2025-04-03  151.295377  3047.0
3    APPLE 2025-04-04  153.046060  3747.0
4    APPLE 2025-04-05  149.531693  1189.0
5   GOOGLE 2025-04-01  149.531726  3734.0
6   GOOGLE 2025-04-02  153.158426  4005.0
7   GOOGLE 2025-04-03  151.534869  5658.0
8   GOOGLE 2025-04-04  149.061051  2899.0
9   GOOGLE 2025-04-05  151.085120  8734.0
10    MSFT 2025-04-01  149.073165  2267.0
11    MSFT 2025-04-02  149.068540  2528.0
12    MSFT 2025-04-03  149.068540     0.0
13    MSFT 2025-04-04  146.173440  4890.0
14    MSFT 2025-04-05  146.550164  9838.0

In [ ]:
##freq = 'B'指的是生成交易日，自动跳过周末
##freq = 'D'指的是生成日历日，包括周末

In [92]:
import pandas as pd
import numpy as np
import os

class DataProcessor:
    def __init__(self,data_dir = './data/'):
        self.data_dir = data_dir
        self.raw_data = None
        self.prices = None

    def load_raw(self):
        df_list = []

        for file in os.listdir(self.data_dir):
            if file.endswith('.csv'):
                file_path = os.path.join(self.data_dir,file)
                df = pd.read_csv(file_path,skiprows = [1])

                ticker = file.replace('.csv','')
                #ticker = str(file.replace(".csv", ""))
                df['ticker'] = ticker
                df['date'] = pd.to_datetime(df['Date'])
                df_list.append(df)

        self.raw_data = pd.concat(df_list,ignore_index = True)
        return self.raw_data
        # why here choose to return a DataFrame instead of a list?
        #what is the difference between this and the original code in day2


    def process_prices(self,price_col = 'Close',fill_method = 'ffill'):
        if self.raw_data is None:
            self.load_raw()
        prices = {}
        for ticker, group in self.raw_data.groupby('ticker'):
            #这里 ticker 返还的首先是ticker，group返还的是这个ticker所对应的所有的数据
            prices[ticker] = group.set_index('date')[price_col]

        self.prices = pd.DataFrame(prices).sort_index()

        if fill_method == 'ffill':
            self.prices = self.prices.ffill()

        return self.prices

    def process_returns(self):
        """输出日收益率矩阵"""
        if self.prices is None:
            self.process_prices()

        return self.prices.pct_change().dropna()
        #what is the meaning of this sentence
        #pct_change() is used for caculagte the difference of percentage
        #dropna() means to drop the first day's data as the zero day does not exist

    def get_stats(self):
        if self.prices is None:
            self.process_prices()
        returns =  self.process_returns()

        stats = pd.DataFrame({
            'mean':returns.mean(),
            'var':returns.var(),
            'skew':returns.skew()
        })

        return stats
if __name__ == '__main__':
    
    processor = DataProcessor("./data/")
    
    # 测试所有功能
    raw = processor.load_raw()
    print("1. 原始数据加载完成:", raw.shape)
    
    prices = processor.process_prices()
    print("\n2. 价格矩阵:")
    print(prices.head())
    
    returns = processor.process_returns()
    print("\n3. 收益率矩阵:")
    print(returns.head())
    
    stats = processor.get_stats()
    print("\n4. 统计指标:")
    print(stats)

1. 原始数据加载完成: (300, 8)

2. 价格矩阵:
                  AAPL        AMZN       GOOGL        MSFT        NVDA
date
2025-01-02  242.525177  220.220001  188.558273  414.568604  138.264694
2025-01-03  242.037827  224.190002  190.907394  419.292877  144.422684
2025-01-06  243.668915  227.610001  195.964020  423.749786  149.381042
2025-01-07  240.894073  222.110001  194.590408  418.322296  140.094086
2025-01-08  241.381409  222.130005  193.057495  420.491272  140.064117

3. 收益率矩阵:
                AAPL      AMZN     GOOGL      MSFT      NVDA
date
2025-01-03 -0.002009  0.018027  0.012458  0.011396  0.044538
2025-01-06  0.006739  0.015255  0.026487  0.010630  0.034332
2025-01-07 -0.011388 -0.024164 -0.007010 -0.012808 -0.062170
2025-01-08  0.002023  0.000090 -0.007878  0.005185 -0.000214
2025-01-10 -0.024104 -0.014361 -0.009848 -0.013214 -0.029976

4. 统计指标:
           mean       var      skew
AAPL  -0.001399  0.000327 -0.462458
AMZN  -0.002313  0.000329 -0.258916
GOOGL -0.003196  0.000437 -0.837549
MSFT  -0.001679  0.000265 -0.437411
NVDA  -0.003216  0.001779 -1.060909